services:
  - type: web
    name: bar-jukebox
    runtime: node
    plan: free
    buildCommand: npm install && python3 -m pip install -r requirements.txt
    startCommand: npm start
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: ADMIN_PASSWORD
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: LASTFM_API_KEY
        sync: false
      - key: BLOCK_EXPLICIT
        value: "true"
